behaviors:
  HillClimber:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1280
      buffer_size: 51200
      learning_rate: 5.0e-5
      beta: 5.0e-2
      epsilon: 0.9
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      use_recurrent: false
      sequence_length: 32
      memory_size: 2048
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.95
      curiosity:
        strength: 0.05
        gamma: 0.95
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 1000
    threaded: true