behaviors:
  HillClimber:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 32768
      learning_rate: 1.0e-4
      beta: 5.0e-2
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 8
    reward_signals:
      extrinsic:
        gamma: 0.975
        strength: 1.0
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 1000
