behaviors:
  HillClimber:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 40960
      learning_rate: 5.0e-5
      beta: 1.0e-2
      epsilon: 1.0
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 6
      use_recurrent: true
      sequence_length: 32
      memory_size: 2048
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.95
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 1000